"""new fields in user model

Revision ID: dd5ae6401f26
Revises: e2901b095278
Create Date: 2022-08-05 20:08:40.688161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5ae6401f26'
down_revision = 'e2901b095278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('admin', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'last_seen')
    op.drop_column('admin', 'about_me')
    # ### end Alembic commands ###
